server:
  port: 7575
spring:  application:    name: api-gateway
  cloud:    gateway:      routes:      - id: truyumservice
        uri: lb://truyum-rest-app
        predicates:
        - Path=/**
        
#eureka: # client:  #  service-url:   #   default-zone: http://localhost:8761/eureka
  #instance:
   # hostname: localhost
      